# Generated by Django 2.0.7 on 2018-07-21 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsitem',
            old_name='title',
            new_name='header',
        ),
    ]
