# Generated by Django 2.0.7 on 2018-07-21 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20180721_1630'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsitem',
            old_name='header',
            new_name='title',
        ),
    ]
